spring:
  application:
    name: kfd-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://rm-cn-nxo4qgihf0001sio.rwlb.rds.aliyuncs.com/kfd_ai_agent
    username: leikooo
    password: dkf@19990621
  ai:
    dashscope:
      api-key: sk-b8ee847437084ebe9af186be32db96d4
      chat:
        options:
          model: qwen-plus
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: gemma3:1b
    mcp:
      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
        stdio:
          servers-configuration: classpath:mcp-servers.json
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kfd.kfdaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  api-key: QBAyn8RQk16qK7JfvkPsjHU2
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG